/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { GenerationMode } from '../services/geminiService';

export type LanguageCode = 'en' | 'fr' | 'es' | 'ru' | 'it' | 'de' | 'ar' | 'zh' | 'pt' | 'hi';

export const languageNameMap: Record<LanguageCode, string> = {
  en: 'English',
  fr: 'French',
  es: 'Spanish',
  ru: 'Russian',
  it: 'Italian',
  de: 'German',
  ar: 'Arabic',
  zh: 'Mandarin Chinese',
  pt: 'Portuguese',
  hi: 'Hindi',
};

type Translation = {
  search: string;
  recent: string;
  madeBy: string;
  generatedBy: string;
  save: string;
  generationMode: string;
  modes: Record<GenerationMode, string>;
};

export const translations: Record<LanguageCode, Translation> = {
  en: {
    search: 'Search',
    recent: 'Recent',
    madeBy: 'Made by',
    generatedBy: 'Content and images generated by Google Gemini',
    save: 'Save',
    generationMode: 'Generation Mode',
    modes: {
      encyclopedia: 'Encyclopedia',
      eli5: 'To a 5-year-old',
      practicalExamples: 'Practical Examples',
      stepByStep: 'Step-by-Step',
      summary: 'Key Points',
      funFacts: 'Fun Facts',
    },
  },
  it: {
    search: 'Cerca',
    recent: 'Recenti',
    madeBy: 'Creato da',
    generatedBy: 'Contenuti e immagini generati da Google Gemini',
    save: 'Salva',
    generationMode: 'Modalità di Generazione',
    modes: {
      encyclopedia: 'Enciclopedia',
      eli5: 'Bambino di 5 anni',
      practicalExamples: 'Esempi Pratici',
      stepByStep: 'Passo-passo',
      summary: 'Sintesi Schematica',
      funFacts: 'Fun Facts',
    },
  },
  fr: {
    search: 'Rechercher',
    recent: 'Récents',
    madeBy: 'Créé par',
    generatedBy: 'Contenu et images générés par Google Gemini',
    save: 'Enregistrer',
    generationMode: 'Mode de Génération',
    modes: {
      encyclopedia: 'Encyclopédie',
      eli5: 'À un enfant de 5 ans',
      practicalExamples: 'Exemples Pratiques',
      stepByStep: 'Étape par Étape',
      summary: 'Points Clés',
      funFacts: 'Faits Amusants',
    },
  },
  es: {
    search: 'Buscar',
    recent: 'Recientes',
    madeBy: 'Hecho por',
    generatedBy: 'Contenido e imágenes generados por Google Gemini',
    save: 'Guardar',
    generationMode: 'Modo de Generación',
    modes: {
      encyclopedia: 'Enciclopedia',
      eli5: 'A un niño de 5 años',
      practicalExamples: 'Ejemplos Prácticos',
      stepByStep: 'Paso a Paso',
      summary: 'Puntos Clave',
      funFacts: 'Datos Curiosos',
    },
  },
  de: {
    search: 'Suchen',
    recent: 'Letzte',
    madeBy: 'Erstellt von',
    generatedBy: 'Inhalte und Bilder von Google Gemini generiert',
    save: 'Speichern',
    generationMode: 'Generierungsmodus',
    modes: {
      encyclopedia: 'Enzyklopädie',
      eli5: 'Für einen 5-Jährigen',
      practicalExamples: 'Praktische Beispiele',
      stepByStep: 'Schritt für Schritt',
      summary: 'Kernpunkte',
      funFacts: 'Wissenswertes',
    },
  },
  ru: {
    search: 'Поиск',
    recent: 'Недавние',
    madeBy: 'Сделано',
    generatedBy: 'Контент и изображения созданы Google Gemini',
    save: 'Сохранить',
    generationMode: 'Режим генерации',
    modes: {
      encyclopedia: 'Энциклопедия',
      eli5: '5-летнему ребенку',
      practicalExamples: 'Практические примеры',
      stepByStep: 'Шаг за шагом',
      summary: 'Ключевые моменты',
      funFacts: 'Интересные факты',
    },
  },
  ar: {
    search: 'بحث',
    recent: 'الأخيرة',
    madeBy: 'صنع من قبل',
    generatedBy: 'المحتوى والصور تم إنشاؤها بواسطة Google Gemini',
    save: 'حفظ',
    generationMode: 'وضع التوليد',
    modes: {
      encyclopedia: 'موسوعة',
      eli5: 'طفل عمره 5 سنوات',
      practicalExamples: 'أمثلة عملية',
      stepByStep: 'خطوة بخطوة',
      summary: 'النقاط الرئيسية',
      funFacts: 'حقائق ممتعة',
    },
  },
  zh: {
    search: '搜索',
    recent: '最近',
    madeBy: '由...制作',
    generatedBy: '内容和图片由 Google Gemini 生成',
    save: '保存',
    generationMode: '生成模式',
    modes: {
      encyclopedia: '百科全书',
      eli5: '给5岁小孩',
      practicalExamples: '实际例子',
      stepByStep: '一步一步',
      summary: '要点总结',
      funFacts: '有趣的事实',
    },
  },
  pt: {
    search: 'Pesquisar',
    recent: 'Recentes',
    madeBy: 'Feito por',
    generatedBy: 'Conteúdo e imagens gerados pelo Google Gemini',
    save: 'Salvar',
    generationMode: 'Modo de Geração',
    modes: {
      encyclopedia: 'Enciclopédia',
      eli5: 'Para uma criança de 5 anos',
      practicalExamples: 'Exemplos Práticos',
      stepByStep: 'Passo a Passo',
      summary: 'Pontos Chave',
      funFacts: 'Curiosidades',
    },
  },
  hi: {
    search: 'खोजें',
    recent: 'हाल का',
    madeBy: 'द्वारा बनाया गया',
    generatedBy: 'सामग्री और चित्र Google Gemini द्वारा उत्पन्न',
    save: 'सहेजें',
    generationMode: 'जनरेशन मोड',
    modes: {
      encyclopedia: 'विश्वकोश',
      eli5: '5 साल के बच्चे के लिए',
      practicalExamples: 'व्यावहारिक उदाहरण',
      stepByStep: 'चरण-दर-चरण',
      summary: 'मुख्य बिंदु',
      funFacts: 'रोचक तथ्य',
    },
  },
};
